FROM ghcr.io/pnpm/pnpm:11
RUN pnpm runtime set node 24 -g
RUN apt update && apt upgrade -y

RUN apt install -y \
ca-certificates \
git \
curl \
ripgrep \
nodejs \
wget

RUN useradd -m -s /bin/bash node
RUN pnpm config set minimumReleaseAge 2880
RUN pnpm add -g --ignore-scripts @earendil-works/pi-coding-agent

USER node
ENV HOME=/home/node
WORKDIR /home/node/workspace

ENTRYPOINT ["pi"]
